name: Deploy to AWS S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: reactstoragewebsite
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ AKIAWMDSV7L372KBDHF6 }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
          SOURCE_DIR: build/
